### ISSUE TITLE
Power-up: A = Speed-up and go Autopilot for 5 seconds 

### ISSUE THREAD

**Issue by gmamaladze** [freeuni-sdp/arkanoid-16#12]
შექმენით Capsule კლასის ვარიანტი. თუ Brick-ს მინიჭებული აქვს ეს კაპსულა ბურთის დაჯახებისას ის ჩამოაგდებს "A" კაპსულას. ამ კაფსულის დაჭრისას 5 წამის განმავლობაში ბურთის სიჩქარე ორმაგდება და ირთვება ავტოპილოტი. ავტოპილოტი მართავს ჩოგანს. ჩოგანის პოზიცია მიყვება ბურთის x კოორდინატს. ამის შედეგად 100% შემთხვევაში ხდება არეკვლა. 5 წამის შემდეგ ჩოგანი ისევ მომხმარებელს ემორჩილება, სიჩქარე უბრუნდება საწყის მნიშვნელობას.

რეალიზაციის ერთ ერთი ვარიანტია Paddle კლასის სპეციფიური იმპლემენტაცია. თქვენი კაფსულა ანაცვლებს ჩოგანს (იხ. ExpandCapsule). ავტოპილოტის მთელი ლოგიკა მოქეცულია ამ ახალ Paddle კლასში. 5 წამის შედეგად უკან დაბრუნების რეალიზაციისათვის შეიძლება დაგჭირდეთ ცალკე ვირტუალური კაფსულა რომელსაც 5 წამის შემდეგ ხელოვნურად დააჯახებთ ჩოგანს.

---
შეავსეთ შესაბამისი პუნქტი ამ Wiki გვერდზე
[Task 2](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-2:-Questions#16-რა-მთავარი-უპირატესობა-აქვს-აქ-გამოყენებულ-modelviewpresenter-პატერნს-გადახედეთ-issue-ებს-და-მოახდინეთ-იმ-issue-ების-იდენტიფიკაცია-რომლების-განხორციელებაც-ვერ-მოხერხდებოდა-ან-გაძნელდებოდა-ამ-პატერნის-არ-გამოყენების-შემთხვევაში-დაასაბუთეთ-რატომ)
[Task 3](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-3:-Expansion#6-speed-up)

**Comment by Megatvini** [comment]
რამდენიმე ბურთის შემთხვევაში როგორ ჯობს ერთი აირჩიოს და იმას გაყვეს თუ ყოველ move-ზე უახლოესს?

**Comment by gmamaladze** [comment]
რაც უფრო მარტივი დასაიმპლემენტირებელია. მნიშვნელოვანია რომ ერთ-ერთის დაკარგვის შემთხვევაში ახალზე გადაერთოს.
