### ISSUE TITLE
Bomb-bricks

### ISSUE THREAD

**Issue by gmamaladze** [freeuni-sdp/arkanoid-16#13]
Bombs – nestled within a formation of blocks. When hit with the ball they explode, carving out small chunks of blocks or setting off major chain reaction with other bombs.

ბომბი აგურისა და ბურთის შეჯახების შემთხვევაში ამ აგურის დაახლოებით 3 უჯრის რადიუსში ხდება "აფეთქება".  "აფეთქება" ნიშნავს იმას რომ  მეზობელ აგურებს ემართებათ ის რაც დაემართებოდათ მათ ბურთი რომ დაჯახებოდა. გაითვალისწინეთ რომ ბურთის დაჯახებისას აგურებს სხვადასხვანაირი რეაქცია აქვთ. ანუ მეზობელი აგურის უბრალოდ გაქრობა გამოსავალი არ არის. მაგალითად მეზობელიც თუ ბომბია ისიც უნდა აფეთქდეს და ჯაჭვური რეაქცია გამოიწვიოს.

---
შეავსეთ შესაბამისი პუნქტი ამ Wiki გვერდზე
[Task 2](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-2:-Questions#21-გაეცანით-single-responsibility-principle-ს-კოდში-მოძებნეთ-მაგალითი-სადაც-დარღვეულია-ეს-წესი-შემოგვთავაზეთ-თუ-როგორ-გამოასწორებდით-აღნიშნულ-ხარვეზს)
[Task 3](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-3:-Expansion#4-bomb-bricks)

**Comment by ggham** [comment]
Bomb brick-ების სადემონსტრაციოდ რაიმე ახალი ლეველი დავამატო?

**Comment by gkiko** [comment]
ჯობია ახალი დაამატო
