### ISSUE TITLE
Common: Score counting

### ISSUE THREAD

**Issue by gmamaladze** [freeuni-sdp/arkanoid-16#26]
ამოცანის მიზანია თამაშის მსვლელობისას ეკრანის ზედა მარჯვენა კუთხეში ჩანდეს რიცხვი, რომელიც რეალურ დროში ასახავს მოთამაშის მიერ დაგროვებულ ქულებს. ქულების რაოდენობა ჩანს რიცხვის სახით ზედა რიგში მარჯვენა მხარეს.  ეს რიგი რეზერვირებულია ქულებისა და სიცოცხლეების საჩვენებლად.

გაითვალისწინეთ რომ ქულების რაოდენობა ნარჩუნდება ლეველიდან ლეველამდე. იხილეთ ScoreCounter-ი რომელიც ითვლის ჯამურად დაგროვილ ქულებს. ქულების რაოდენობის UI-ში განსაახლებლად დაგჭირდებათ Observer-პატერნის გამოყენება. იხ. არასრული იმპლემენტაცია StatusUpdateListener. დაასრულეთ CellUpdateListener-ის ანალოგიურად. ითანამშრომელეთ ამოცანასტან #30.

---
შეავსეთ შესაბამისი პუნქტი ამ Wiki გვერდზე
[Task 2](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-2:-Questions#2-აღწერეთ-რა-ცვლილებები-დაგჭირდებოდათ-თუ-soundplayer-ს-მოვათავსებდით-view-ის-შრეში)
[Task 3](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-3:-Expansion#12-score-counting)

**Comment by gkiko** [comment]
სანამ ქულა არ განახლდება მანამდე არ ჩანს ეკრანზე. ვეცადე გამომესწორებინა, მაგრამ უფრო მეტი გავაფუჭე 3cca63064ac16c6c8797b3ef9860a29d73d6ab51
