### ISSUE TITLE
Power-down: K = Kill - Same as a ball loss

### ISSUE THREAD

**Issue by gmamaladze** [freeuni-sdp/arkanoid-16#29]
შექმენით Capsule კლასის ვარიანტი. თუ Brick-ს მინიჭებული აქვს ეს კაპსულა ბურთის დაჯახებისას ის ჩამოაგდებს "K"  კაპსულას. ამ კაპსულის დაჭერას მოთამაშემ თავი უნდა აარიდოს. თუ შემთხვევით მოძრაობისას მაინც დაიჭირა იწვევს იგივე ეფექტს რაც ბურთის დაკარგვას ახლავს.

ბურთის დაკარგვაზე რეაქციის იმპლემენტაცია მოხდება სხვა ამოცანაში #30 . თქვენი კაპსულის იმპლემენტაციამ არ უნდა მოახდინოს იგივე კოდის გამეორება.

---
შეავსეთ შესაბამისი პუნქტი ამ Wiki გვერდზე
[Task 2](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-2:-Questions#8-დააკვირდით-რორგორ-გამოიყენება-level-და-roombuilder-ახსენით-დანიშნულება-აღწერეთ-მსგავსება-თუ-შეინიშნება-strategy-პატერნთან)
[Task 3](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-3:-Expansion#24-kill-capsule)

**Comment by nikoloz14** [comment]
ამ ამოცანის შესასრულებლად უნდა დაველოდო #30 -ის დასრულებას, თუ ჩემით შემიძლია რამის გაკეთება, რაც სიცოცხლეებს ეხება?

**Comment by gkiko** [comment]
შენი წილი დაწერე. თუ მაგალითად ამოცანა 30-ის ფუნქციონალი დაგჭირდება, stub მეთოდები შეგიძლია შემოიღო, რომ შენი კოდის გაშვება და შემოწმება შეძლო.

**Comment by gmamaladze** [comment]
@gkiko საჭიროებისას უფრო კონკრეტული რეკომენდაციაც შეგიძლია მისცე.

**Comment by nikoloz14** [comment]
აქ ორი ვარიანტია, რადგან LifeLostListener-ი Paddle-ს აქვს, რომელი უფრო სწორი იქნება?
1) KillerCapsule-ს interact მეთოდში, გამოვიძახო Paddle-ს რაღაც მეთოდი, რომელიც, თავისმხრივ, Listener-ს გააქტიურებს(რადგან KillerCapsule-ს პირდაპირი წვდომა არ აქვს LifeLostListener-ზე)
2) Paddle-ს interact მეთოდში შევამოწმო KillerCapsul-ზე და აქვე გამოვიძახო Listener-ი

**Comment by gkiko** [comment]
ის ვარიანტი განიხილე, რომ KillCapsule-ში შეჯახების შემდეგ ამოგეღო ყველა ბურთი ოთახიდან და მოგეკლა. აღარ დაგჭირდებოდა პედლზე ლისენერების დაყენება.
