### ISSUE TITLE
Common: Paddle lifes - lost ball removes one life and restarts

### ISSUE THREAD

**Issue by gmamaladze** [freeuni-sdp/arkanoid-16#30]
ოთახის იატაკი გაკეთებულია KillerBrick-ებისგან.
ბურთის KillerBrick-თან ინტერაქცია უნდა იწვევდეს სიცოცხლის დაკარგვას.
მოიფიქრეთ რომელი ობიექტის თვისებაა სიცოცხლეების რაოდენობა. შეეცადეთ არსებული კლასების "გაფართოებით" დაწეროთ ეს ფუნქციონალი([OCP](https://en.wikipedia.org/wiki/Open/closed_principle))
გაითვალისწინეთ რომ თამაშის მსვლელობაში ერთზე მეტი ბურთის არსებობაა შესაძლებელი.
ამ შემთხვევაში სიცოცხლის დაკარგვა ბოლო ბურთის დაკარგვას ნიშნავს.

---
შეავსეთ შესაბამისი პუნქტი ამ Wiki გვერდზე
[Task 2](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-2:-Questions#18-კოდში-რამოდენიმე-ადგილას-გამოიყენება-if-other-instanceof-brick--ის-მაგვარი-ტიპის-შემმოწმებელი-პირობითი-ოპერატორები-რომლებსაც-ხანდახან-მოყვება-type-cast-ი-რომელ-solid-პრინციპს-არღვევს-ასეთი-მიდგომა-მოიყვანეთ-მაგალითი-თუ-როგორ-შეცვლიდით-კოდს-იმსათვის-რომ-ball-ის-interact-მეთოდში-არ-მომხდარიყო-კასტი)
[Task 3](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-3:-Expansion)

**Comment by gkiko** [comment]
@wrinkl3 რა ეტაპზე ხარ?

**Comment by wrinkl3** [comment]
@gkiko კოდს ვარჩევ ჯერ, წერა არ დამიწყია.

**Comment by aazizyan** [comment]
@wrinkl3 როდის აპირებ დაწერას ? ზედმეტად ბევრი რამე არის დამოკიდებული ამ issue-ზე.

**Comment by wrinkl3** [comment]
@aazizyan ახლა ვიწყებ, კარგ შემთხვევაში ხვალ იქნება. არვიცოდი სხვა issue-ები პირდაპირ ამაზე დამოკიდებული თუ იყო.

**Comment by gkiko** [comment]
@wrinkl3 ნაჩქარევად არ დაწერო კოდი. გაიაზრე და შემდეგ შეიტანე ცვლილებები

**Comment by wrinkl3** [comment]
@gkiko სათაურში წერია რო restart-იც ამ issue-ს ნაწილია, მარა დანარჩენ პირობაში ეს ნახსენები არცაა. ბურთის დაკარგვისას მთლიანი ეკრანი რესეტდება, თუ მხოლოდ ბურთი და ჩოგანი?

**Comment by gkiko** [comment]
თუ უკანასკნელი სიცოცხლე დაკარგე, თამაში მთავრდება. თუ სიცოცხლე კიდევ
გრჩება, მაშინ ბურთი და ჩოგანი რესეტდება მარტო
On Apr 12, 2016 3:13 AM, "wrinkl3" <notifications@github.com> wrote:

@gkiko <https://github.com/gkiko> სათაურში წერია რო restart-იც ამ issue-ს
ნაწილია, მარა დანარჩენ პირობაში ეს ნახსენები არცაა. ბურთის დაკარგვისას
მთლიანი ეკრანი რესეტდება, თუ მხოლოდ ბურთი და ჩოგანი?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/freeuni-sdp/arkanoid-16/issues/30#issuecomment-208608782>

**Comment by wrinkl3** [comment]
@gkiko შემდეგი იდეა მაქვს: შევქმნი listener-ს, რომლის გამოძახებაც შეუძლია ნებსმიერ brick-ს და გამოძახებისას დაარეზეტებს ბურთს (თუ სიცოცხლეები კიდევ დარჩენილია) ან დაასრულებს თამაშს (თუ აღარაა). სავარაუდოდ გეიმში უნდა დავწერო ეს ლისტენერი, ან ცალკე კლასი შევქმნა რომელსაც გეიმთან ექნება წვდომა. 
ასევე ცალკე counter-ს შევქმნი ბურთების მიმდინარე რაოდენობის სათვლელად და Room-ში შევინახავ. ბურთების რაოდენობის შემოწმება (და შესაბამისად სიცოცხლის დაკლება/არდაკლება) ცალკეული ლეველების იმპლემენტატორებს უნდა ევალებოდეს, რადგან ამისი წესები ყველგან ერთნაირი არაა (მაგალითან Sliding Wall-ს ბურთების რაოდენობა სულ არ აინტერესებს).

**Comment by gkiko** [comment]
`Ball`-ს გადაეცი `Game`, როგორც ჩოგანს გადაეცემა `Game` `PaddleChangedListener`-ით. კედელთან დაჯახებისას ბურთი `Game`-ს შეატყობინებს, რომ სიცოცხლე დააკლდა. პედლსაც გადაეცი `Game` იმავე ლისენერით, რომ `KillerCapsule`-სთან დაჯახებისას სიცოცხლე დააკლოს.

დასაფიქრებელია, ფუნქციონალის გამეორება ხომ არ გამოგვდის. ამავე ფუნქციონალის იმპლემენტაციას ცდილობს `SinkingWall` და `ScrollingWall`

**Comment by nikoloz14** [comment]
აქ ორი ვარიანტია, რადგან LifeLostListener-ი Paddle-ს აქვს, რომელი უფრო სწორი იქნება?
1) KillerCapsule-ს interact მეთოდში, გამოვიძახო Paddle-ს რაღაც მეთოდი, რომელიც, თავისმხრივ, Listener-ს გააქტიურებს
2) Paddle-ს interact მეთოდში შევამოწმო KillerCapsul-ზე და აქვე გამოვიძახო Listener-ი

**Comment by gkiko** [comment]
Task 2-ის კოდი შეამოწმე თუ მუშაობს?
