### ISSUE TITLE
Paddle leaves game bounds

### ISSUE THREAD

**Issue by aazizyan** [freeuni-sdp/arkanoid-16#35]
პადლი გადის თამაშის საზღვრებს გარეთ. საჭიროა პოზიციის შემოწმება ყოველი გამოძრავების მერე.

**Comment by gmamaladze** [comment]
:+1:

**Comment by gmamaladze** [comment]
სხვა შესაძლო ვარიანტი იქნებოდა FrameBrick-თან inetraction-ის შემთხვევაში FrameBrick-იდან Paddle-ის გაჩერება.

**Comment by gkiko** [comment]
@aazizyan -ის გზა მარტივად იწერება, მაგრამ `Game`-ის `move` მეთოდი ყოველ ჯერზე ცდილობს პედლის წაძვრას, `paddleMoved` მეთოდი კი ყოველივე ჯერზე უკან აბრუნებს.
ანუ მოდელში პედლი მოძრაობს წინ და უკან, მაგრამ პრეზენტერამდე ვერ აღწევს ეს ეფექტი.

**Comment by aazizyan** [comment]
@gmamaladze -ის გზით გადავაკეთე. თუმცა ისარის აშვებაზე პედლის გაჩერება, მაინც კარგი აზრია. @gkiko

**Comment by aazizyan** [comment]
@gmamaladze @gkiko პედლის გაჩერების ერთ-ერთი გზაა, რომ `move` მეთოდში სიჩქარის ვექტორი გავუნულოთ, ყოველი მიმატების მერე. რა აზრის ხართ ამაზე ?

**Comment by gkiko** [comment]
კიდევ ერთი გზაა პედლში გავიტანოთ გაჩერების ფუნქცინალი.

```java
public void move() {
    prevPosition = getPosition();
    super.move();
}

@Override
public boolean isAlive() {
    return _isAlive;
}
```

მომავალში შეიძლება აღმოჩნდეს რომ პედლს უამრავი მოვალეობა აქვს. `interact` მეთოდები დიდ საფრთხეს მალავენ :skull:

**Comment by aazizyan** [comment]
@gkiko -ს გაჩერების ვარიანტი იმუშავებს მარტო მაშინ, თუ სამყაროს სიგანე პედლის სიგანის

**Comment by gmamaladze** [comment]
#36 მოგვარდა
