### ISSUE TITLE
Stop paddle if arrow keys are released

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/arkanoid-16#36]
Paddle მოძრაობს მხოლოდ მაშინ, როდესაც მომხმარებელი აჭერს ისრებს <kbd>&#8592;</kbd> <kbd>&#8594;</kbd>

###### გადმოვიდა #35-დან

**Comment by gkiko** [comment]
ამ issue-ს ვხურავ, რადგან ძალიან მარტივი შესაცვლელია paddle-ის ქცევა. RoomPresenter->execute()

```java
switch (command) {
    case None:
        _direction = Direction.NONE;
        break;
...
```

**Comment by gmamaladze** [comment]
@gkiko არა, მთლად მასე მარტივიც არ არის, მაგრამ დავფიქსე უკვე. 8775fffdc7e5741fcb8a9c465ba94e591f8ddd37
