### ISSUE TITLE
Ball leaves Room

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/arkanoid-16#37]
პრობლემის გასამეორებლად ითამაშეთ პირველი ტური. paddle-ით აისხლიტეთ ბურთი და არ მისცეთ იატაკთან შეხების საშუალება. დაახლოებით 5-ე ასხლეტვისას ბურთი გავარდება ეკრანის მარჯვენა კედლიდან აგურთან დაჯახებისას.

![screen shot 2016-03-30 at 8 01 30 pm](https://cloud.githubusercontent.com/assets/2578308/14148955/dbce894a-f6b2-11e5-93b5-f2dc2286ff60.png)

**Comment by gmamaladze** [comment]
მარჯვენა კედელი გაასქელე.
ანუ FrameBuilder-ში მარჯვენა FrameBrick-ის სისქე გახადე 2, 1 ის ნაცვლად.
(არ ვაღადაობ)
