### ISSUE TITLE
Ball moves between bricks

### ISSUE THREAD

**Issue by aazizyan** [freeuni-sdp/arkanoid-16#38]
ბოლო ვერსიაში, ბურთი ზოგჯერ იკიდებს ბრიქებს საერთოდ და გადის მათში.

**Comment by gmamaladze** [comment]
ამ კომიტის მერე ნახეთ 267088fe407b5b00d4cb5c5485b427f4c3c2f545

**Comment by aazizyan** [comment]
@gmamaladze   ბოლო ვერსიაში, რომელიც დევს გიტზე, არის ეს ბაგი. თამაში რომ დაიწყება პადლი საერთოდ არ გავამოძრავოთ და ცოტა ხანში ბურთი გაივლის 2 ბრიქს შორის მარჯვენა მხარეს. თამაშის მსვლობისას შეიძლება კიდე გამეორდეს მსგავსი შემთხვევა მარცხენა მხარეს.

![screenshot from 2016-04-01 14-17-43](https://cloud.githubusercontent.com/assets/6974115/14204328/a7195604-f814-11e5-802f-ef0dd22c31a6.png)

**Comment by gmamaladze** [comment]
2 ბრიქს შორის გავლა მემგონი ფიჩად უნდა გამოვაცხადოთ. იმიტომ რომ: 

**თავიდან ბურთი მოდელირებული იტო როგორც წრე.**
წრეების მართკუთხედებთან კოლიზიის ლოგიკა ან არასრული უნდა დამეტოვებინა, მაშინ ქონდა ბაგები, ან უნდა გამერთულებინა უაზრო გეომეტრიით, რაც ჩვენი ამოცანისათვის არარელევანტური იყო.

**ამ ჩეინჯსეთში წრე შეიცვალა წერტილით**
წერტილის მართკუდხედთან კოლიზია ბევრად მარტივია. სამაგიეროდ წერტილს არ აქვს ზომა და ღარებში გაძრომას იწყებს. გამოსავალი ამ შემთხვევაში მარტივია. ღარები უნდა გავაუქმოთ. ორიგინალ თამაშშიც არ არის ღარები.

de49bf305b081626b608fb64c60ac9d790681e0c

@aazizyan დახურეთ issue თუ გადაწყვეტილება მისაღებია.

**Comment by aazizyan** [comment]
@gmamaladze შეგვეძლო დაგვეტოვებინა ღარები და კოლიზიის ლოგიკაში ჩაგვესვა, რომ ბურთი გადაიკვეთება მართკუთხედთან, თუ ბურთის ცენტრი მართკუთხედშია ან ბურთი იკვეთება მართკუთხედის რომელიმე გვერდთან.

**Comment by gkiko** [comment]
მგონი ამაზე დიდი ტასკები გვაქვს მოსაგვარებელი. შევეშვათ ამ ტასკს.

**Comment by gmamaladze** [comment]
:+1:
