### ISSUE TITLE
Brick disappears / gets stuck at the corner of the room

### ISSUE THREAD

**Issue by nikachx** [freeuni-sdp/arkanoid-16#39]
When ball hits one of the corners of the room gets stuck or disappears at all.
[Screen shot](http://imgur.com/vI2gIfN)

**Comment by gmamaladze** [comment]
გადაამოწმეთ ამ 52e975738d12d63a5101b488d9c7c98406aac93d კომიტის შემდეგაც თუ ხდება კუთხიდან გაძრომა.

**Comment by gkiko** [comment]
მსგავდი პრობლემ #37 
მაინც გვაქვს ეს პრობლემა.
პრობლემის გასამეორებლად ჩართეთ მეორე ტური და დადექით ოთახის მარჯვენა ბოლოში.
