### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by aazizyan** [freeuni-sdp/arkanoid-16#41]
#10 გადაჭრისას, როდესაც საკმაოდ ბევრი ბრიქია უკვე დაფაზე, აღმოჩნდა, რომ თამაში იჭედება. უფრო ზუსტად იციკლება `while`-ში Ball.java ხაზი 48. ყოველი იტერაციის მერე ვაბეჭდინებდი მიმდინარე დროს. გაჭედვის მერე ყრიდა ერთნაირ დროებს დიდი პორციებით, რითაც დავასკვენი, რომ პრობლემა ამ ციკლშია.

**Comment by gmamaladze** [comment]
ეს ხდება როდესაც შემთხვევით კედელი მაშინ ჩამოიწევა როდესაც ბურთი აგურს ქვევით იმყოფება და ზევითკენ მიფრინავს. ამ მომენტში კედელი თუ ჩამოიწია ბურთი მოხვდება აგურის შიგნით და ვეღარ გამოდის.

ამ პრობლემის მოგვარება ოფციონალურია და არ არის თქვენი ამოცანის ნაწილი. თუ შეძლებთ მოაგვარეთ თუ არა და ჩვენ მივხედავთ.

**Comment by gkiko** [comment]
მგონი გავასწორე ეს პრობლემა. ეხლა ავტვირთავ კოდს
