### ISSUE TITLE
Redundant hierarchy

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/arkanoid-16#42]
რა როლი აქვს `RoomBuilder` ინტერფეისს?

![diagram](https://cloud.githubusercontent.com/assets/2578308/14403384/47fce2f6-fe65-11e5-8efd-9668c191fa01.png)

ხომ არ აჯობებს `FrameBuilder`-ს სახელი რომ გადავარქვათ `RoomBuilder`-ად, `RoomBuilder` ინტერფეისი კი წავშალოთ?

**Comment by gmamaladze** [comment]
შეიძლება, მაშინ შევზღუდავთ თეორიულად შესძლო ოთახევის რაოდენობას ოთხკედლიანი ოტახებით, რომლებშიც მხოლოდ იატაკის გამოცვლა მოსულა. ოთახები სადაც მაგალითად მარჯვენა და მარცხენა კედელი არ რასებობს (ისგრძეში უსასრულო და კამერა დაყვება ბურთს) არარ გვექნება.

რადგან ასეთი ეგზოტიკური ოთახის ვარიანტები წელს (შარშანდელი სნეიკისგან განსხვავებით) აღარ გვაქვს შეგვიძლია გავაუქმოთ, მაგრამ აბსოლუტურად ზადმეტიც არ არის.

**Comment by gkiko** [comment]
გასაგებია. დავტოვოთ როგრც არის.

`FramaBuilder` -> `RectangleRoomBuilder`
