### ISSUE TITLE
A bug in ExpandedPaddle

### ISSUE THREAD

**Issue by gkink** [freeuni-sdp/arkanoid-16#43]
როდესაც Paddle იჭერს ExpandCapsule-ს თუ Paddle რომელიმე კედელთან იმდენად ახლოსაა, რომ გაზრდისას კედლის საზღვრებს სცდება, კედელში იჭედება და აღარ მოძრაობს.

**Comment by aazizyan** [comment]
@gkink ნახე. წესით გასწორდა.

**Comment by gkink** [comment]
მეც გავასწორე არ ამიფუშავს უბრალოდ. ნუ თუ მუშაობს იყოს მე უბრალოდ ExpandedPaddle-ს გადავუტვირთე interact მეთოდი. ჯერ მშობლის მეთოდს იძახებს მერე კიდე ამოწმებს თუ FrameBrick-s დაეჯახა და თან ფრეიმბრიკთან გადაფარვა აქვს მაშინ ფრეიმბრიკის პოზიციიდან თავისი width-ით ვაშორებ.

**Comment by aazizyan** [comment]
@gkink დაფუშე თუ გაასწორე მაშინ. ჩემ ვერსიაში ჯერ კიდევ არის ბაგი.

**Comment by aazizyan** [comment]
@gkink უფრო მარტივად გამოვიდა. exchange მეთოდში იყო ბაგი. ყოველთვის სეტავდა თავის პოზიციას. დავფუშავ ეხლა და ნახე.

**Comment by gkink** [comment]
მე უკვე ავფუშე ნახე და რომელიმე დატოვე მერე

**Comment by aazizyan** [comment]
@gkink იყოს შენი : ))

**Comment by gkink** [comment]
მეც შევამჩნიე ალბათ მარცხენა კედლის გამო გახსენი და გავასწორე უკვე, ნახე აბა.

**Comment by gkink** [comment]
@aazizyan

**Comment by aazizyan** [comment]
@gkink რამდენად კარგია, რომ ExpandedPaddle-ი ინახავს თავის ზომებს ფროფერთიებად ?

**Comment by gkink** [comment]
@aazizyan წინა ვერსიაში 9 და 1 ეწერა და რადგანაც ბევრჯერ გამოვიყენე სახელი დავარქვი. ისე მართალი ხარ static final უნდა იყოს, ფროფერთიდ ნამდვილად არ გვჭირდება

**Comment by aazizyan** [comment]
@gkiko გადახედე და დახურე, თუ ყველაფერი კარგადაა.
