### ISSUE TITLE
Power-up: P = Paddle - Grey (Gives The Player an extra paddle)

### ISSUE THREAD

**Issue by gmamaladze** [freeuni-sdp/arkanoid-16#7]
შექმენით Capsule კლასის ვარიანტი. თუ Brick-ს მინიჭებული აქვს ეს კაპსულა ბურთის დაჯახებისას ის ჩამოაგდებს "P" კაპსულას. ამ კაფსულის დაჭრისას Paddle-ს მოემატება სიცოცხლეების რაოდენობა. სიცოცხლეების რაოდენობა ჩანს ვარსკვლავების სახით ზედა რიგში მარცხენა მხარეს ***. 
ეს რიგი რეზერვირებულია ქულებისა და სიცოცხლეების საჩვენებლად.

მოიფიქრეთ სად დათვლით სიცოცხლეების რაოდენობას. გაითვალისწინეთ რომ სიცოცხლეების რაოდენობა ნარჩუნდება ლეველიდან ლეველამდე. ანალოგიისათვის იხილეთ ScoreCounter-ი რომელიც ითვლის ჯამურად დაგროვილ ქულებს. ქულების რაოდენობის UI-ში განსაახლებლად დაგჭირდებათ Observer-პატერნის გამოყენება.

---
შეავსეთ შესაბამისი პუნქტი ამ Wiki გვერდზე
[Task 2](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-2:-Questions#17-გაეცანით-rectangle-და-circle-კლასების-canoverlap-მეთოდების-იმპლემენტაციას-აქტუალური-იმპლემენტაციის-თანახმად-ნებისმიერი-ახალი-ფიგურის-დამატება-გამოიწვევდა-თითოეული-ფიგურის-კლასის-canoverlap-მეთოდების-რაოდენობის-გაზრდას-ეს-არღვევს-open-close-პრინციპს-დაასაბუთეთ-რატომ-შემოგვთავაზეთ-ისეთი-დიზაინი-რომელიც-ფიგურის-მაგ-სამკუთხედის-დამატებისას-არ-გამოიწვევს-ტველა-ფიგურის-კოდის-მოდიფიკაციას)
[Task 3](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-3:-Expansion#14-gives-the-player-an-extra-paddle)

**Comment by Rshalika** [comment]
#30 ში ნათქვამია რომ მოიფიქრეთ სად შეინახავთ სიცოცხლეებსო "მოიფიქრეთ რომელი ობიექტის თვისებაა სიცოცხლეების რაოდენობა."
რეალურად ისე გამოდის რომ ყველას გვიწევს ცალცალკე სიცოცხლი მთვლელის შემოღება (#30 არ არის იმპლემენტირებული).

ერთი ვარიანტია ScoreCounter ს შეეძლოს სიცოცხლეების დათვლაც ანუ ფუნქციონალი გაფართოვდეს მისი. მაშინ game გადასცემგა rooms ქაუნთერს (როგორც level.build ში გადაეცემა) და Capsule კი თავის მხრივ room ის counters შეცვლიდა. 
მეორე ვარიანტია  level.build ს მესამე პარამეტრი ჩავაწოდოთ ლაივ ქაუნთერის სახით 

მორიდებული შეკითხვა : 
  რას მირჩევთ ? "მოიფიქრეთ რომელი ობიექტის თვისებაა სიცოცხლეების რაოდენობა" ეს გავაკეთო ?

**Comment by gkiko** [comment]
სატესტოდ შეგიძლია `LiveCounter` შექმნა. გაითვალისწინე რომ ქვედა კედელზე ბურთის დაცემისას, მოძრავი კედლის უძრავ კედელთან შეჯახებისას და K კაფსულას აღებისას სიცოცხლე აკლდება. ამიტომ უნდა ვცადოთ ზოგადი კოდის დაწერა. ზუსტად არ ვიცი რა გზა აჯობებს 😞

**Comment by Rshalika** [comment]
@gkiko  ჩემი ნომრით(7) wiki არ არსებობს. შინაარსობრივად 14 ნომერი შეესაბამება ვიკიდან და იმას შევავსებ

**Comment by gkiko** [comment]
შენ რაც აღწერე Task 2-ში არც ეგ გზა აგვარებს ocp-ის პრობლემას. `canOverlap(Rectangle other)` მეთოდი რომ შემოვიღო `ShapeVisitor` ინტეფეისში, ყველა შვილ კლასში მომიწევს მეთოდის იმპლემენტაცია ნებისმიერ შემთხვევაში.

@gmamaladze მახსოვს ადრე ახსენე რომ "slave" კლასიშ შემოღება არის გამოსავალი, სადაც ყველას ყველასთან `canOverlap` მეთოდი ეწერებოდა
