### ISSUE TITLE
Basic bricks: white, orange, etc + gold

### ISSUE THREAD

**Issue by gmamaladze** [freeuni-sdp/arkanoid-16#8]
color | point
-------|-------
White | 50 pts.
Orange | 60 pts.
Light Blue | 70 pts.
Green | 80 pts.
Red | 90 pts.
Dark Blue | 100 pts.
Light Orange | 110 pts.
Yellow | 120 pts.
Gold | Indestructible!

ბურთის და აგურის შეხებისას

1. ბურთი იცვლის მიმართულებას
2. აგური ქრება(არა _Gold_)
3. თუ აგური გაქრა, მოთამაშეს ეწერება ქულა

ქულების დასათვლელად გამოიყენეთ #26-ის მიხედვით დაწერილი ფუნქციონალი.

---
შეავსეთ შესაბამისი პუნქტი ამ Wiki გვერდზე
[Task 2](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-2:-Questions#14-იპოვეთ-მინიმუმ-ორი-ადგილი-სადაც-dependency-injection-ი-არის-გამოყენებული-აღწერეთ-რა-კონკრეტულ-შესაძლებლობებს-გვიხსნის-თქვენს-მიერ-ნაპოვნ-მაგალითებში-di-ს-გამოყენება)
[Task 3](https://github.com/freeuni-sdp/arkanoid-16/wiki/Task-3:-Expansion#19-brick-types-with-points)

**Comment by gkiko** [comment]
strategy პატერნი რატომ გმამოიყენე?

> ახალი ფერის და ქულის დამატება იქნება ძალიან მარტივი

უფრო მარტივი იქნებოდა სვიჩში ფერის მიხედვით პირდაპირ ქულა რომ დაგებრუნებინა
